2024-08-12 12:32:18 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}
2024-08-12 12:32:28 | INFO    | __main__:claim_epic_games:97 | Try to flush cookie - {'task': 'claim_epic_games'}
2024-08-12 12:32:31 | INFO    | epic_games.agent:_login:237 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games&__cf_chl_rt_tk=NcDXm8ZwhB6dAQvsDqIXGGqRCkO042.2EeaK7oYH3Yg-1723437151-0.0.1.1-5524'}
2024-08-12 12:33:01 | WARNING    | epic_games.agent:authorize:266 | 执行超时 - {'task': 'authorize', 'retry': 0}
2024-08-12 12:33:03 | INFO    | epic_games.agent:_login:237 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games&__cf_chl_rt_tk=9Mtqqm_mJPyg8zDZ6EbYiaMob7lY7CIaog0HhgwFkhQ-1723437183-0.0.1.1-6442'}
2024-08-12 12:33:33 | WARNING    | epic_games.agent:authorize:266 | 执行超时 - {'task': 'authorize', 'retry': 1}
2024-08-12 12:33:36 | INFO    | epic_games.agent:_login:237 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games&__cf_chl_rt_tk=Rko5mLOCcb7CCAvxOZYfBpXpQOTrpHfzDPUJRgf69fg-1723437216-0.0.1.1-6420'}
2024-08-12 12:34:06 | WARNING    | epic_games.agent:authorize:266 | 执行超时 - {'task': 'authorize', 'retry': 2}
2024-08-12 12:34:06 | ERROR    | __main__:run:158 | An error has been caught in function 'run', process 'MainProcess' (3766), thread 'MainThread' (139703756057472): - {}
Traceback (most recent call last):
  File "/home/runner/work/HI-plus/HI-plus/epic/src/claim.py", line 162, in <module>
    asyncio.run(run())
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/home/runner/work/HI-plus/HI-plus/epic/src/claim.py", line 158, in run
    await agent.stash()
  File "/home/runner/work/HI-plus/HI-plus/epic/src/claim.py", line 151, in stash
    await self.claim_epic_games(context)
  File "/home/runner/work/HI-plus/HI-plus/epic/src/claim.py", line 98, in claim_epic_games
    if await epic.authorize(page):
  File "/home/runner/work/HI-plus/HI-plus/epic/src/epic_games/agent.py", line 269, in authorize
    raise RuntimeError(f"Failed to flush token - agent={self.__class__.__name__}")
RuntimeError: Failed to flush token - agent=EpicGames
